name: Publish docs website via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Caching action
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ github.ref }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force
