name: Publish docs website via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Caching action
        uses: actions/cache@v3
        with:
          path: .cache
          key: ${{ github.ref }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.X
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force
